{
  "concurrency": {
    "cancel-in-progress": true,
    "group": "build-${{ github.ref }}"
  },
  "jobs": {
    "check": {
      "needs": "get-check-names",
      "runs-on": "nix",
      "steps": [
        {
          "uses": "https://data.forgejo.org/actions/checkout@v4",
          "with": {
            "submodules": true
          }
        },
        {
          "name": "Install SSH key",
          "uses": "https://github.com/webfactory/ssh-agent@v0.9.0",
          "with": {
            "ssh-private-key": "${{ secrets.SSH_PRIVATE_KEY }}"
          }
        },
        {
          "name": "Login to attic",
          "run": "nix run nixpkgs#attic-client login fly https://attic-cache.fly.dev ${{ secrets.ATTIC_KEY }}\n"
        },
        {
          "continue-on-error": true,
          "name": "nix-fast-build",
          "run": "nix run github:Mic92/nix-fast-build -- \\\n  --skip-cached \\\n  --no-nom \\\n  --attic-cache system \\\n  -j 4 \\\n  --eval-workers 4 \\\n  --eval-max-memory-size 2048 \\\n  --retries 2 \\\n  --no-link \\\n  --flake '.#checks.x86_64-linux.\"${{ matrix.checks }}\"'\n"
        }
      ],
      "strategy": {
        "fail-fast": false,
        "matrix": {
          "checks": "${{ fromJson(needs.get-check-names.outputs.checks) }}"
        }
      },
      "timeout-minutes": 180
    },
    "check-nixos": {
      "needs": "get-check-names",
      "runs-on": "nix",
      "steps": [
        {
          "uses": "https://data.forgejo.org/actions/checkout@v4",
          "with": {
            "submodules": true
          }
        },
        {
          "name": "Install SSH key",
          "uses": "https://github.com/webfactory/ssh-agent@v0.9.0",
          "with": {
            "ssh-private-key": "${{ secrets.SSH_PRIVATE_KEY }}"
          }
        },
        {
          "name": "Login to attic",
          "run": "nix run nixpkgs#attic-client login fly https://attic-cache.fly.dev ${{ secrets.ATTIC_KEY }}\n"
        },
        {
          "name": "nix-fast-build",
          "run": "nix run github:Mic92/nix-fast-build -- \\\n  --skip-cached \\\n  --no-nom \\\n  --attic-cache system \\\n  -j 4 \\\n  --eval-workers 4 \\\n  --eval-max-memory-size 2048 \\\n  --retries 2 \\\n  --no-link \\\n  --flake '.#checks.x86_64-linux.\"${{ matrix.checks }}\"'\n"
        }
      ],
      "strategy": {
        "fail-fast": false,
        "matrix": {
          "checks": "${{ fromJson(needs.get-check-names.outputs.checks-nixos) }}"
        }
      },
      "timeout-minutes": 350
    },
    "get-check-names": {
      "outputs": {
        "checks": "${{ steps.get-check-names.outputs.checks }}",
        "checks-nixos": "${{ steps.get-check-names.outputs.checks-nixos }}"
      },
      "runs-on": "nix",
      "steps": [
        {
          "uses": "https://data.forgejo.org/actions/checkout@v4",
          "with": {
            "submodules": true
          }
        },
        {
          "name": "Install SSH key",
          "uses": "https://github.com/webfactory/ssh-agent@v0.9.0",
          "with": {
            "ssh-private-key": "${{ secrets.SSH_PRIVATE_KEY }}"
          }
        },
        {
          "id": "get-check-names",
          "run": "all_checks=\"$(nix --accept-flake-config eval --json .#checks.x86_64-linux --apply builtins.attrNames)\"\nnixos_checks=\"$(echo \"$all_checks\" | jq -c '[.[] | select(startswith(\"configurations/nixos/\"))]')\"\nif [ \"${{ github.event_name }}\" != workflow_dispatch ]; then\n  nixos_checks=\"$(echo \"$nixos_checks\" | jq -c --argjson skip '[\"configurations/nixos/iso\"]' 'map(select(IN($skip[]) | not))')\"\nfi\necho \"checks=$(echo \"$all_checks\" | jq -c '[.[] | select(startswith(\"configurations/nixos/\") | not)]')\" >> $GITHUB_OUTPUT\necho \"checks-nixos=$nixos_checks\" >> $GITHUB_OUTPUT\n"
        }
      ]
    }
  },
  "name": "Build",
  "on": {
    "push": {},
    "workflow_dispatch": {}
  }
}
