{
  "jobs": {
    "get-check-names": {
      "outputs": {
        "checks": "${{ steps.get-check-names.outputs.checks }}"
      },
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Remove unused toolkits",
          "run": "sudo rm -rf $AGENT_TOOLSDIRECTORY\nsudo rm -rf /usr/local/.ghcup\nsudo rm -rf /usr/local/share/powershell\nsudo rm -rf /usr/local/share/chromium\nsudo rm -rf /usr/local/lib/node_modules\nsudo rm -rf /usr/local/lib/heroku\nsudo rm -rf /var/lib/docker/overlay2\nsudo rm -rf /home/linuxbrew\nsudo rm -rf /home/runner/.rustup\nsudo rm -rf /etc/ssh/sshd_config.d/50-cloud-init.conf\n"
        },
        {
          "uses": "actions/checkout@v4",
          "with": {
            "submodules": true
          }
        },
        {
          "name": "Create attic netrc",
          "run": "sudo mkdir -p /etc/nix /etc/determinate\necho \"machine attic-cache.fly.dev login automated password ${{ secrets.ATTIC_KEY }}\" | sudo tee /etc/nix/netrc > /dev/null\necho '{\"authentication\":{\"additionalNetrcSources\":[\"/etc/nix/netrc\"]}}' | sudo tee /etc/determinate/config.json > /dev/null\ngit config --global url.\"https://${{ secrets.GH_TOKEN_FOR_UPDATES }}@github.com\".insteadOf https://github.com\n"
        },
        {
          "uses": "DeterminateSystems/nix-installer-action@v22",
          "with": {
            "extra-conf": "fallback = true\nhttp-connections = 25\nmax-substitution-jobs = 16\nconnect-timeout = 15\nstalled-download-timeout = 15\ndownload-attempts = 100\naccept-flake-config = true\nnetrc-file = /etc/nix/netrc\nsubstituters = https://yazi.cachix.org https://helix.cachix.org https://cache.nixos.org https://attic-cache.fly.dev/system?priority=50 https://nix-community.cachix.org https://hyprland.cachix.org https://anyrun.cachix.org https://prismlauncher.cachix.org https://nix-gaming.cachix.org\ntrusted-public-keys = yazi.cachix.org-1:Dcdz63NZKfvUCbDGngQDAZq6kOroIrFoyO064uvLh8k= helix.cachix.org-1:ejp9KQpR1FBI2onstMQ34yogDm4OgU2ru6lIwPvuCVs= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= system:qjMAtak3MMVYM2B3EoLvNG9duRTrjdNS65RTagsr+y4= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc= anyrun.cachix.org-1:pqBobmOjI7nKlsUMV25u9QHa9btJK65/C8vnO3p346s= prismlauncher.cachix.org-1:9/n/FGyABA2jLUVfY+DEp4hKds/rwO+SCOtbOkDzd+c= nix-gaming.cachix.org-1:nbjlureqMbRAxR1gJ/f3hxemL9svXaZF/Ees8vCUUs4=\n",
            "flakehub": false
          }
        },
        {
          "name": "Install SSH key",
          "uses": "webfactory/ssh-agent@v0.9.0",
          "with": {
            "ssh-private-key": "${{ secrets.SSH_PRIVATE_KEY }}"
          }
        },
        {
          "name": "Login to attic",
          "run": "nix run nixpkgs#attic-client login fly https://attic-cache.fly.dev ${{ secrets.ATTIC_KEY }}\n"
        },
        {
          "id": "get-check-names",
          "run": "checks=\"$(nix --accept-flake-config --allow-import-from-derivation eval --json .#checks.x86_64-linux --apply builtins.attrNames)\"\necho \"checks=$checks\" >> $GITHUB_OUTPUT\n"
        }
      ]
    }
  },
  "name": "Eval",
  "on": {
    "push": {},
    "workflow_call": {
      "outputs": {
        "checks": {
          "description": "JSON array of check names",
          "value": "${{ jobs.get-check-names.outputs.checks }}"
        }
      }
    }
  }
}
